FROM node:22-alpine3.22

WORKDIR /app

COPY .next/standalone/ ./

COPY public ./public

COPY .next/static ./.next/static

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

EXPOSE 3000

CMD ["node", "server.js"]
