/**
 * Typed copy layer — Spanish-first UI strings.
 *
 * `ui` is the source of truth: every key resolves to a Spanish string.
 * `en` is the English fallback mirror, used only for incomplete migrations so
 * no label ever renders empty. Primary flows (auth, billing, whatsapp) SHALL
 * always resolve to the Spanish value.
 *
 * Use `copy(namespace, key)` or access `ui.namespace.key` directly. Both are
 * TypeScript-typed: referencing an unknown key fails the build.
 */

export const ui = {
  common: {
    retry: "Reintentar",
    retrying: "Reintentando…",
    back: "Atrás",
    cancel: "Cancelar",
    save: "Guardar",
    processing: "Procesando…",
    unexpectedError: "Ocurrió un error inesperado. Inténtalo de nuevo.",
    contactSupport: "Contactar soporte",
  },
  auth: {
    title: "Crea tu cuenta",
    subtitle: "Empieza con",
    home: "Inicio",
    fullName: "Nombre completo",
    fullNamePlaceholder: "Juan Pérez",
    email: "Correo electrónico",
    emailPlaceholder: "tu@empresa.com",
    continue: "Continuar",
    organizationName: "Nombre de la organización",
    organizationNamePlaceholder: "Acme S.A.S.",
    industry: "Industria",
    industryTechnology: "Tecnología",
    industryFinance: "Finanzas",
    industryHealthcare: "Salud",
    industryRetail: "Comercio",
    industryOther: "Otro",
    creating: "Creando…",
    createAccount: "Crear cuenta",
    emailSentTitle: "Revisa tu correo",
    emailSentIntro: "Enviamos un enlace de verificación a",
    emailSentCta: "Haz clic en el enlace para completar tu registro.",
    backToSignIn: "Volver a iniciar sesión",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    signIn: "Inicia sesión",
  },
  billing: {
    plansEyebrow: "Elige tu plan",
    plansTitle: "Escala tus aprobaciones sin límites",
    monthlyBilling: "Los planes se facturan mensualmente.",
    polarPaymentNote: "El pago se procesa con Polar.",
    mpPaymentNote:
      "Paga con tarjeta internacional (Polar) o PSE / Nequi / tarjeta colombiana (MercadoPago).",
    quotasUpdateNote: "Los puestos y las cuotas de facturación se actualizan al completar el pago.",
    loadingPlans: "Cargando planes…",
    loadPlansError: "No se pudieron cargar los planes. Inténtalo de nuevo.",
    activeSubscription: "Suscripción activa",
    activeSubscriptionHint: "Cancela tu suscripción actual antes de seleccionar un nuevo plan.",
    checkoutError: "Error al procesar el pago",
    noPlans: "No hay planes disponibles.",
    processingCheckout: "Procesando tu pago…",
    checkoutCreationFailed: "No se pudo crear el pago. Inténtalo de nuevo.",
    perMonth: "/mes",
    perYear: "/año",
    seatsIncluded: "puestos incluidos",
    invoicesPerMonth: "facturas por mes",
    aiCreditsPerPeriod: "créditos por período",
    intervalMonthly: "Mensual",
    intervalAnnual: "Anual",
    intervalToggleAria: "Alternar período de facturación",
    comparisonTitle: "Comparar planes",
    comparisonSeats: "Puestos incluidos",
    comparisonInvoices: "Facturas por mes",
    comparisonAiCredits: "Créditos de IA",
    paymentVerifiedTitle: "Pago confirmado",
    paymentVerifiedBody: "Tu plan está activo.",
    paymentErrorTitle: "No pudimos confirmar tu pago",
    paymentErrorBody: "Tu plan aún no está activo. Reintenta el pago para activarlo.",
    retryCheckout: "Reintentar pago",
    currentPlan: "Plan actual",
    processingDots: "Procesando…",
    internationalCard: "Tarjeta internacional",
    mpCard: "PSE / Nequi / tarjeta colombiana",
    understood: "Entendido",
    close: "Cerrar",
    closePlansAria: "Cerrar modal de planes",
    restrictedTitle: "Acceso a suscripción restringido",
    restrictedBody:
      "No tienes permiso para gestionar la suscripción o la facturación. Contacta al administrador de tu espacio de trabajo si crees que es un error.",
    loadSubscriptionTitle: "No pudimos cargar tu suscripción",
    refreshOrSupport: "Actualiza la página o contacta al soporte.",
    redirecting: "Redirigiendo al panel…",
    proPlan: "Plan Pro",
    unlockTitle: "Desbloquea toda la experiencia de automatización de AP",
    unlockBody:
      "Procesa facturas más rápido, elimina duplicados y evita el cierre de mes. Suscríbete para recuperar el acceso al panel.",
    viewPlans: "Ver planes",
    talkToSales: "Hablar con ventas",
    planSnapshot: "Resumen del plan",
    contactSales: "Contactar ventas",
    cancelAnytime: "cancela cuando quieras",
    activateHelp: "Te ayudaremos a activar el plan correcto.",
    invoicesRemaining: "Facturas restantes",
    invoicesUsedPeriod: "Facturas usadas en el período",
    trialEnds: "El período de prueba termina",
    noActiveSubMp:
      "Es posible que tu suscripción de MercadoPago haya sido cancelada o que tu método de pago haya vencido. Reinicia tu plan para continuar donde quedaste.",
    noActiveSubPolar:
      "Es posible que tu método de pago haya vencido o que la suscripción se haya cancelado. Reinicia tu plan para continuar donde quedaste.",
    customerNotFoundMp:
      "No pudimos vincular tu organización a una suscripción activa. Suscríbete con PSE o Nequi para reactivarla y vincularemos todo automáticamente.",
    customerNotFoundPolar:
      "No pudimos vincular tu organización a un cliente Polar activo. Suscríbete con el mismo correo que usas para iniciar sesión y vincularemos todo automáticamente.",
    unknownErrorBody:
      "No pudimos verificar tu suscripción en este momento. Inténtalo de nuevo o contacta al soporte.",
    invoicesMonthIncluded: "facturas / mes incluidas",
    invoicesMonthIncludedDesc:
      "Uso medido con protección de excesos. Consulta el consumo en tiempo real.",
    flatSubscription: "suscripción plana",
    flatSubscriptionDesc:
      "Facturación predecible alineada con las necesidades de tu equipo de finanzas.",
    includedWithPlan: "Incluido con tu plan actual.",
    approvalsAnomaly: "Aprobaciones y detección de anomalías",
    approvalsAnomalyDesc:
      "Mantén responsables a los aprobadores y detecta riesgos antes de que lleguen al ERP.",
    exportReadyPayments: "Pagos listos para exportar",
    exportReadyPaymentsDesc:
      "Genera archivos de pago que se integran directamente con NetSuite y SAP.",
    of: "de",
    polarConfigRequired: "Configuración de Polar requerida",
    polarConfigDesc:
      "Agrega POLAR_ACCESS_TOKEN y POLAR_WEBHOOK_SECRET a tu entorno para activar la gestión de suscripciones.",
    checkAgain: "Verificar de nuevo",
    talkToSupport: "Hablar con soporte",
    noActivePlan: "Sin plan activo",
    noActivePlanBody:
      "Elige un plan para desbloquear las automatizaciones. Serás redirigido a una página de pago segura para confirmar tu suscripción.",
    browsePlans: "Explorar planes",
    currentPlanEyebrow: "Plan actual",
    customPlan: "Plan personalizado",
    billedMonthly: "facturado mensualmente",
    billedVia: "Facturado vía",
    renewsOn: "Se renueva el",
    scheduledToEnd: "Finalización programada",
    scheduledToEndBody:
      "Tu suscripción terminará el {date}. Reanúdala antes para mantener las automatizaciones activas.",
    switchPlansHint:
      "Para cambiar de plan, cancela tu suscripción actual. Cuando termine, elige un nuevo plan y suscríbete de nuevo desde esta página.",
    planBenefits: "Beneficios del plan",
    resumeSubscription: "Reanudar suscripción",
    scheduleCancellation: "Programar cancelación",
    refreshStatus: "Actualizar estado",
    processingRequest: "Procesando solicitud…",
    unableLoadSubscription: "No se pudo cargar la suscripción",
    actionFailed: "La acción falló",
    invoiceUsage: "Uso de facturas",
    usageResetsOn: "El uso se reinicia el {date}.",
    trackUsage: "Consulta cuántas facturas has procesado en este período.",
    invoicesProcessed: "facturas procesadas",
    invoicesRemainingSuffix: "facturas restantes",
    aiCredits: "Créditos de IA",
    aiCreditsBody: "Créditos disponibles para funciones de IA este período. {resets}",
    aiResetsOn: "Se reinician el {date}.",
    creditsRemaining: "créditos restantes",
    inOutTokens: "entrada / salida de tokens",
    confirmCancellation: "Confirmar cancelación",
    cancelDialogBody:
      "Escribe CANCEL para terminar tu suscripción al cierre del período actual de facturación. Conservarás el acceso hasta {date}.",
    endOfTerm: "el final del término",
    typeCancelPlaceholder: "Escribe CANCEL para confirmar",
    headsUp: "Aviso",
    headsUpBody:
      "La cancelación se aplica al finalizar el período actual. Puedes reanudar la suscripción antes de esa fecha para mantener tu automatización activa.",
    keepSubscription: "Mantener suscripción",
    subscriptionOverview: "Resumen de la suscripción",
    loadingPlanDetails: "Cargando los detalles de tu plan…",
    statusInactive: "Inactivo",
    statusCancelsSoon: "Por cancelar",
    statusTrialing: "En prueba",
    statusPastDue: "Vencida",
    statusGrace: "Período de gracia",
    statusActive: "Activo",
  },
  whatsapp: {
    title: "Integración de WhatsApp Business",
    description:
      "Conecta tu cuenta de WhatsApp Business para recibir y gestionar mensajes.",
    active: "Activo",
    inactive: "Inactivo",
    connectTitle: "Conecta WhatsApp",
    connectBody:
      "Conserva tu aplicación móvil de WhatsApp Business y tu historial de chats mientras habilitas la mensajería automatizada. Meta te guiará para elegir tu negocio, número y verificación.",
    connectButton: "Conectar WhatsApp",
    microSteps: [
      "Conectando tu WhatsApp…",
      "Validando la conexión…",
      "Configurando la entrega de mensajes…",
      "¡Todo listo! Tu WhatsApp está activo.",
    ] as const,
    connectionFailedTitle: "No se pudo conectar",
    connectionFailedBody: "No se pudo conectar WhatsApp durante el aprovisionamiento.",
    errorCodePrefix: "Código de error:",
    errorCodeHint: "contacta al soporte si esto continúa.",
    tryAgain: "Intentar de nuevo",
    connected: "WhatsApp conectado",
    businessPhone: "Teléfono de negocio",
    phoneNumberId: "ID de número de teléfono",
    wabaId: "ID de WABA",
    advancedSettings: "Configuración avanzada",
    webhookCallbackUrl: "URL de webhook",
    webhookCallbackHint:
      "Configura esta URL en el panel de WhatsApp Business de Meta en la sección Webhook.",
    copy: "Copiar",
    callbackCopied: "URL copiada al portapapeles",
    phoneNumberIdHint: "Se encuentra en el panel de negocios de Meta en WhatsApp > API Setup",
    businessPhoneHint: "Formato E.164 con código de país (ej. +57 para Colombia)",
    webhookSecretHintExisting: "Déjalo vacío para mantener el valor actual",
    webhookSecretHintNew:
      "Requerido para nuevas conexiones. Se encuentra en el panel de negocios de Meta.",
    webhookSecretPlaceholderExisting: "Déjalo vacío para mantener el actual",
    webhookSecretPlaceholderNew: "Ingresa el secreto de webhook",
    verifyTokenHintExisting: "Déjalo vacío para mantener el valor actual",
    verifyTokenHintNew: "Requerido para nuevas conexiones. Tú defines este token.",
    verifyTokenPlaceholderExisting: "Déjalo vacío para mantener el actual",
    verifyTokenPlaceholderNew: "Ingresa el token de verificación",
    wabaIdHint: "ID de la cuenta de WhatsApp Business",
    accessTokenPlaceholderExisting: "Déjalo vacío para mantener el actual",
    accessTokenPlaceholderNew: "Ingresa el token de acceso",
    accessTokenHintExisting: "Déjalo vacío para mantener el valor actual",
    accessTokenHintNew: "Requerido para enviar mensajes. Se genera en el panel de negocios de Meta.",
    apiVersionHint: "Versión de la API de WhatsApp Cloud (predeterminada: v21.0)",
    graphApiUrlHint: "URL base de Graph API (predeterminada: https://graph.facebook.com)",
    appIdHint: "ID de la app de WhatsApp Business (opcional)",
    appIdPlaceholder: "Opcional",
    saveChanges: "Guardar cambios",
    messagesBeingReceived: "Se están recibiendo mensajes",
    messageReceivingPaused: "La recepción de mensajes está en pausa",
    footerNote: "Requiere configuración previa de la app de Meta (Embedded Signup).",
    loadFailedTitle: "No se pudo cargar la configuración",
    loadFailedBody: "No se pudo obtener la configuración de WhatsApp. Inténtalo de nuevo.",
    validationPhoneRequired:
      "El ID de número de teléfono y el teléfono de negocio son obligatorios",
    validationWebhookRequired:
      "El secreto de webhook y el token de verificación son obligatorios para nuevas conexiones",
    connectFailed: "No se pudo conectar WhatsApp durante el aprovisionamiento.",
    alreadyConnected: "Esta organización ya está conectada.",
    connectionInProgress: "Ya hay una conexión en curso.",
    metaSdkUnavailable: "El SDK de Meta no está disponible.",
    noAuthCode: "Meta no devolvió un código de autorización. Inténtalo de nuevo.",
    signupConfigError: "No se pudo cargar la configuración de inicio de sesión de WhatsApp.",
    connectionFailed: "No se pudo conectar.",
  },
  inbox: {
    title: "Bandeja de entrada",
    tabAll: "Todas",
    tabActive: "Activas",
    tabClosed: "Cerradas",
    tabArchived: "Archivadas",
    channelAll: "Todas",
    channelWhatsapp: "WhatsApp",
    channelInstagram: "Instagram",
    emptyInstagram:
      "Aún no hay mensajes de Instagram — conecta Instagram en Configuración para comenzar",
    emptyWhatsapp:
      "Aún no hay mensajes de WhatsApp — conecta WhatsApp en Configuración para comenzar",
    emptyAll: "No se encontraron conversaciones",
    goToSettings: "Ir a configuración →",
    timeJustNow: "ahora",
    timeMin: "hace {n} min",
    timeHour: "hace {n} h",
    timeDay: "hace {n} d",
    unknownContact: "Desconocido",
    unreadAria: "Mensajes no leídos",
    threadEmpty: "Aún no hay mensajes. Envía una respuesta para iniciar la conversación.",
    typeImage: "Imagen",
    typeVideo: "Video",
    typeAudio: "Audio",
    typeDocument: "Documento",
    typeLocation: "Ubicación",
    threadErrorTitle: "Error al cargar los mensajes",
    threadErrorDesc: "No se pudieron cargar los mensajes. Inténtalo de nuevo.",
    listErrorTitle: "Error al cargar las conversaciones",
    listErrorDesc: "No se pudieron cargar las conversaciones. Inténtalo de nuevo.",
    noConversationSelected: "Ninguna conversación seleccionada",
    selectConversationHint:
      "Selecciona una conversación de la lista para ver los mensajes, o conecta un canal en Configuración para empezar a recibir mensajes.",
    goToWhatsappSettings: "Ir a la configuración de WhatsApp →",
    goToInstagramSettings: "Ir a la configuración de Instagram →",
  },
  dashboard: {
    title: "Panel",
    subtitle: "Un resumen de la actividad de tu espacio de trabajo.",
    kpiOpenConversations: "Conversaciones abiertas",
    kpiOpenConversationsHint: "Entre WhatsApp e Instagram",
    kpiContacts: "Contactos",
    kpiContactsHint: "En tu CRM",
    kpiDeals: "Negocios",
    kpiDealsHint: "En todos los pipelines",
    dealsByStage: "Negocios por etapa",
    dealsByStageDesc: "Dónde están tus negocios abiertos ahora mismo.",
    noDeals: "Aún no hay negocios. Crea tu primer pipeline en CRM.",
    recentActivity: "Actividad reciente",
    recentActivityDesc: "Últimas notas, llamadas y eventos del sistema.",
    noActivity: "Aún no hay actividad registrada.",
    quickActions: "Acciones rápidas",
    qaOpenInbox: "Abrir bandeja de entrada",
    qaOpenInboxDesc: "Responde conversaciones pendientes",
    qaManageCrm: "Gestionar CRM",
    qaManageCrmDesc: "Contactos, empresas y negocios",
    qaKnowledgeBase: "Base de conocimiento",
    qaKnowledgeBaseDesc: "Busca documentos y chatea con el asistente",
    qaWorkspaceSettings: "Configuración del espacio de trabajo",
    qaWorkspaceSettingsDesc: "Equipo, módulos, facturación e integraciones",
    noStage: "Sin etapa",
  },
  agent: {
    panelTitle: "Sugerencia del asistente IA",
    panelErrorTitle: "No se pudieron cargar las sugerencias",
    panelErrorDesc: "Inténtalo de nuevo para ver las sugerencias del asistente.",
    approveSend: "Aprobar y enviar",
    sendEdited: "Enviar editado",
    edit: "Editar",
    reject: "Rechazar",
    settingsTitle: "Asistente IA de WhatsApp",
    settingsDescription:
      "Configura cómo el agente redacta y responde mensajes en tus conversaciones.",
    loadErrorTitle: "Error al cargar",
    loadErrorBody: "No se pudo cargar la configuración del asistente IA.",
    mode: "Modo",
    modeCopilot: "Copiloto (sugiere respuestas, un humano aprueba)",
    modeAutopilot: "Autopiloto (responde solo dentro de la ventana)",
    modeHint:
      "Copiloto redacta borradores. Autopiloto envía respuestas autónomas solo si todas las reglas se cumplen.",
    tone: "Tono de voz",
    toneFormal: "Formal (usted)",
    toneCasual: "Informal (tú/vos)",
    toneHint: "Registro usado en las respuestas generadas.",
    brandVoice: "Voz de la marca",
    brandVoicePlaceholder:
      "Ej: Atendemos con calidez y rapidez, siempre en español colombiano.",
    autopilotStart: "Ventana autopiloto (inicio)",
    autopilotEnd: "Ventana autopiloto (fin)",
    timezone: "Zona horaria",
    maxDailyMessages: "Límite de mensajes diarios (0 = ilimitado)",
    maxDiscount: "Descuento máximo permitido (%)",
    killSwitch: "Interruptor de emergencia",
    killSwitchHint: "Bloquea todos los envíos del agente inmediatamente.",
    forbiddenTerms: "Términos prohibidos (nunca usarlos en respuestas)",
    removeAria: "Quitar {term}",
    forbiddenPlaceholder: "Ej: garantía total, envío gratis",
    escalateTerms: "Temas de escalamiento (derivar a un humano)",
    escalateHint: "Si el cliente menciona estos temas, el agente nunca responde solo.",
    escalatePlaceholder: "Ej: abogado, legal, garantía, demanda",
    consentRequired: "Consentimiento requerido (Ley 1581)",
    consentHint:
      "Solicita autorización de tratamiento de datos antes de responder autónomamente.",
    consentMessage: "Mensaje de consentimiento",
    consentPlaceholder:
      "Hola, para atenderte necesitamos tu autorización para el tratamiento de tus datos personales conforme a la Ley 1581. ¿Nos autorizas? (Responde sí o acepto).",
    saveConfig: "Guardar configuración",
  },
  onboarding: {
    businessTitle: "Cuéntanos de tu negocio",
    businessSubtitle:
      "Esto nos ayuda a preparar tu asistente de IA para que responda por WhatsApp.",
    whatsappReadinessLabel: "¿Tienes WhatsApp Business?",
    whatsappReadinessHint:
      "El asistente podrá redactar y responder mensajes cuando lo conectes.",
    readinessAlready: "Sí, ya tengo WhatsApp Business",
    readinessPlanning: "Aún no, pero quiero configurarlo",
    readinessNo: "No por ahora",
    businessGoalLabel: "¿Cuál es tu principal objetivo?",
    businessGoalPlaceholder:
      "Ej: atender consultas de clientes, recibir pedidos, facturar…",
    businessGoalHint: "Puedes cambiarlo más adelante desde la configuración.",
    checklistTitle: "Primeros pasos",
    checklistSubtitle:
      "Completa estos pasos para dejar tu espacio de trabajo listo.",
    checklistProgress: "{done} de {total} completados",
    stepConnectWhatsApp: "Conecta WhatsApp",
    stepConnectWhatsAppDesc:
      "Recibe y responde mensajes automáticamente con tu número.",
    stepChoosePlan: "Elige un plan",
    stepChoosePlanDesc: "Desbloquea las automatizaciones de tu asistente.",
    stepMeetAssistant: "Conoce a tu asistente",
    stepMeetAssistantDesc:
      "El asistente redacta respuestas para que tú las apruebes.",
    stepOpenInbox: "Abre tu bandeja de entrada",
    stepOpenInboxDesc: "Revisa y responde tus primeras conversaciones.",
    statusDone: "Completado",
    statusTodo: "Pendiente",
    assistantIntroTitle: "Conoce a tu asistente",
    assistantIntroBody:
      "Tu asistente de WhatsApp redacta respuestas para tus clientes y tú las apruebas antes de enviarlas. Aprende sobre tu negocio a medida que llegan los mensajes.",
    assistantIntroKnowledgeTitle: "Base de conocimiento",
    assistantIntroKnowledgeBody:
      "Carga documentos sobre tus productos, precios y políticas para que el asistente responda con precisión.",
    assistantIntroCta: "Configurar asistente",
    assistantIntroDismiss: "Más tarde",
  },
} as const;

/** English fallback mirror. Only used when a Spanish value is missing. */
export const en = {
  common: {
    retry: "Retry",
    retrying: "Retrying…",
    back: "Back",
    cancel: "Cancel",
    save: "Save",
    processing: "Processing…",
    unexpectedError: "An unexpected error occurred. Please try again.",
    contactSupport: "Contact support",
  },
  auth: {
    title: "Create your account",
    subtitle: "Get started with",
    home: "Home",
    fullName: "Full Name",
    fullNamePlaceholder: "John Doe",
    email: "Email",
    emailPlaceholder: "you@company.com",
    continue: "Continue",
    organizationName: "Organization Name",
    organizationNamePlaceholder: "Acme Inc",
    industry: "Industry",
    industryTechnology: "Technology",
    industryFinance: "Finance",
    industryHealthcare: "Healthcare",
    industryRetail: "Retail",
    industryOther: "Other",
    creating: "Creating…",
    createAccount: "Create Account",
    emailSentTitle: "Check your email",
    emailSentIntro: "We sent a verification link to",
    emailSentCta: "Click the link to complete your signup.",
    backToSignIn: "Back to Sign In",
    alreadyHaveAccount: "Already have an account?",
    signIn: "Sign in",
  },
  billing: {
    plansEyebrow: "Choose your plan",
    plansTitle: "Scale approvals without hitting limits",
    monthlyBilling: "Plans are billed monthly.",
    polarPaymentNote: "Payment is processed through Polar.",
    mpPaymentNote:
      "Pay with international card (Polar) or PSE / Nequi / Colombian card (MercadoPago).",
    quotasUpdateNote: "Seats and invoice quotas update immediately after checkout completes.",
    loadingPlans: "Loading plans...",
    loadPlansError: "Failed to load plans. Please try again.",
    activeSubscription: "Active subscription",
    activeSubscriptionHint:
      "Cancel your current subscription before selecting a new plan.",
    checkoutError: "Checkout Error",
    noPlans: "No plans available.",
    processingCheckout: "Processing your checkout…",
    checkoutCreationFailed: "Failed to create the checkout. Please try again.",
    perMonth: "/month",
    perYear: "/year",
    seatsIncluded: "seats included",
    invoicesPerMonth: "invoices per month",
    aiCreditsPerPeriod: "credits per period",
    intervalMonthly: "Monthly",
    intervalAnnual: "Annual",
    intervalToggleAria: "Toggle billing interval",
    comparisonTitle: "Compare plans",
    comparisonSeats: "Seats included",
    comparisonInvoices: "Invoices per month",
    comparisonAiCredits: "AI credits",
    paymentVerifiedTitle: "Payment confirmed",
    paymentVerifiedBody: "Your plan is active.",
    paymentErrorTitle: "We couldn't confirm your payment",
    paymentErrorBody: "Your plan is not active yet. Retry the payment to activate it.",
    retryCheckout: "Retry payment",
    currentPlan: "Current Plan",
    processingDots: "Processing…",
    internationalCard: "International card",
    mpCard: "PSE / Nequi / Colombian card",
    understood: "Got it",
    close: "Close",
    closePlansAria: "Close plans modal",
    restrictedTitle: "Subscription access restricted",
    restrictedBody:
      "You don't have permission to manage subscription or billing settings. Contact your workspace administrator if you believe this is an error.",
    loadSubscriptionTitle: "We couldn't load your subscription",
    refreshOrSupport: "Please refresh the page or reach out to support.",
    redirecting: "Redirecting to dashboard...",
    proPlan: "Pro Plan",
    unlockTitle: "Unlock the full AP automation experience",
    unlockBody:
      "Process invoices faster, eliminate duplicates, and stay ahead of the month-end crunch. Subscribe now to regain access to the dashboard.",
    viewPlans: "View pricing plans",
    talkToSales: "Talk to sales",
    planSnapshot: "Plan snapshot",
    contactSales: "Contact sales",
    cancelAnytime: "cancel anytime",
    activateHelp: "We'll help you activate the right plan.",
    invoicesRemaining: "Invoices remaining",
    invoicesUsedPeriod: "Invoices used this period",
    trialEnds: "Trial ends",
    noActiveSubMp:
      "Your MercadoPago subscription may have been canceled or your payment method may have expired. Restart your plan to continue where you left off.",
    noActiveSubPolar:
      "Your payment method may have expired or the subscription was canceled. Restart your plan to continue where you left off.",
    customerNotFoundMp:
      "We couldn't match your organization to an active subscription. Subscribe via PSE or Nequi to reactivate it, and we'll link everything automatically.",
    customerNotFoundPolar:
      "We couldn't match your organization to an active Polar customer. Subscribe using the same email you used to sign in, and we'll link everything automatically.",
    unknownErrorBody:
      "We couldn't verify your subscription at the moment. Please retry or contact support.",
    invoicesMonthIncluded: "invoices / month included",
    invoicesMonthIncludedDesc:
      "Metered usage with overage protection. Track consumption in real time.",
    flatSubscription: "flat subscription",
    flatSubscriptionDesc:
      "Predictable billing aligned with your finance team's needs.",
    includedWithPlan: "Included with your current plan.",
    approvalsAnomaly: "Approvals & anomaly detection",
    approvalsAnomalyDesc:
      "Keep approvers accountable and surface risk before it hits ERP.",
    exportReadyPayments: "Export-ready payments",
    exportReadyPaymentsDesc:
      "Generate payment files that drop straight into NetSuite and SAP.",
    of: "of",
    polarConfigRequired: "Polar configuration required",
    polarConfigDesc:
      "Add POLAR_ACCESS_TOKEN and POLAR_WEBHOOK_SECRET to your environment to enable subscription management.",
    checkAgain: "Check again",
    talkToSupport: "Talk to support",
    noActivePlan: "No active plan",
    noActivePlanBody:
      "Choose a plan to unlock automations. You'll be redirected to a secure checkout page to confirm your subscription.",
    browsePlans: "Browse plans",
    currentPlanEyebrow: "Current plan",
    customPlan: "Custom plan",
    billedMonthly: "billed monthly",
    billedVia: "Billed via",
    renewsOn: "Renews on",
    scheduledToEnd: "Scheduled to end",
    scheduledToEndBody:
      "Your subscription will end on {date}. Resume before then to keep automations running.",
    switchPlansHint:
      "To switch plans, cancel your current subscription. Once it ends, choose a new plan and subscribe again from this page.",
    planBenefits: "Plan benefits",
    resumeSubscription: "Resume subscription",
    scheduleCancellation: "Schedule cancellation",
    refreshStatus: "Refresh status",
    processingRequest: "Processing request…",
    unableLoadSubscription: "Unable to load subscription",
    actionFailed: "Action failed",
    invoiceUsage: "Invoice usage",
    usageResetsOn: "Usage resets on {date}.",
    trackUsage: "Track how many invoices you've processed this period.",
    invoicesProcessed: "invoices processed",
    invoicesRemainingSuffix: "invoices remaining",
    aiCredits: "AI credits",
    aiCreditsBody: "Credits available for AI features this period. {resets}",
    aiResetsOn: "Resets on {date}.",
    creditsRemaining: "credits remaining",
    inOutTokens: "in / out tokens",
    confirmCancellation: "Confirm cancellation",
    cancelDialogBody:
      "Type CANCEL to end your subscription at the close of your current billing period. You'll keep access until {date}.",
    endOfTerm: "the end of the term",
    typeCancelPlaceholder: "Type CANCEL to confirm",
    headsUp: "Heads up",
    headsUpBody:
      "Cancellation takes effect after the current term. You can resume the subscription before that date to keep your automation running.",
    keepSubscription: "Keep subscription",
    subscriptionOverview: "Subscription overview",
    loadingPlanDetails: "Loading your plan details…",
    statusInactive: "Inactive",
    statusCancelsSoon: "Cancels soon",
    statusTrialing: "Trialing",
    statusPastDue: "Past due",
    statusGrace: "Grace period",
    statusActive: "Active",
  },
  whatsapp: {
    title: "WhatsApp Business Integration",
    description: "Connect your WhatsApp Business Account to receive and manage messages.",
    active: "Active",
    inactive: "Inactive",
    connectTitle: "Connect WhatsApp",
    connectBody:
      "Keep your mobile WhatsApp Business app and chat history while enabling automated messaging. Meta will guide you through picking your business, number, and verification.",
    connectButton: "Connect WhatsApp",
    microSteps: [
      "Connecting your WhatsApp...",
      "Verifying Coexistence session...",
      "Establishing secure token & webhooks...",
      "All set! Your WhatsApp is live.",
    ] as const,
    connectionFailedTitle: "Connection failed",
    connectionFailedBody: "WhatsApp connection failed during provisioning.",
    errorCodePrefix: "Error code:",
    errorCodeHint: "contact support if this persists.",
    tryAgain: "Try again",
    connected: "WhatsApp connected",
    businessPhone: "Business phone",
    phoneNumberId: "Phone number ID",
    wabaId: "WABA ID",
    advancedSettings: "Advanced settings",
    webhookCallbackUrl: "Webhook Callback URL",
    webhookCallbackHint:
      "Configure this URL in your Meta WhatsApp Business Dashboard under Webhook settings.",
    copy: "Copy",
    callbackCopied: "Callback URL copied to clipboard",
    phoneNumberIdHint: "Found in Meta Business Dashboard under WhatsApp > API Setup",
    businessPhoneHint: "E.164 format with country code (e.g. +57 for Colombia)",
    webhookSecretHintExisting: "Leave blank to keep the existing value unchanged",
    webhookSecretHintNew:
      "Required for new connections. Found in Meta Business Dashboard.",
    webhookSecretPlaceholderExisting: "Leave blank to keep current",
    webhookSecretPlaceholderNew: "Enter webhook secret",
    verifyTokenHintExisting: "Leave blank to keep the existing value unchanged",
    verifyTokenHintNew: "Required for new connections. You define this token.",
    verifyTokenPlaceholderExisting: "Leave blank to keep current",
    verifyTokenPlaceholderNew: "Enter verify token",
    wabaIdHint: "WhatsApp Business Account ID",
    accessTokenPlaceholderExisting: "Leave blank to keep current",
    accessTokenPlaceholderNew: "Enter access token",
    accessTokenHintExisting: "Leave blank to keep the existing value unchanged",
    accessTokenHintNew: "Required for sending messages. Generate in Meta Business Dashboard.",
    apiVersionHint: "WhatsApp Cloud API version (default: v21.0)",
    graphApiUrlHint: "Base URL for Graph API (default: https://graph.facebook.com)",
    appIdHint: "WhatsApp Business App ID (optional)",
    appIdPlaceholder: "Optional",
    saveChanges: "Save changes",
    messagesBeingReceived: "Messages are being received",
    messageReceivingPaused: "Message receiving is paused",
    footerNote: "Requiere configuracion previa de la app de Meta (Embedded Signup).",
    loadFailedTitle: "Failed to load configuration",
    loadFailedBody: "Could not fetch WhatsApp configuration. Please try again.",
    validationPhoneRequired: "Phone Number ID and Business Phone are required",
    validationWebhookRequired:
      "Webhook Secret and Verify Token are required for new connections",
    connectFailed: "WhatsApp connection failed during provisioning.",
    alreadyConnected: "This organization is already connected.",
    connectionInProgress: "A connection is already in progress.",
    metaSdkUnavailable: "The Meta SDK is not available.",
    noAuthCode: "Meta did not return an authorization code. Please try again.",
    signupConfigError: "Could not load the WhatsApp signup configuration.",
    connectionFailed: "Connection failed",
  },
  inbox: {
    title: "Inbox",
    tabAll: "All",
    tabActive: "Active",
    tabClosed: "Closed",
    tabArchived: "Archived",
    channelAll: "All",
    channelWhatsapp: "WhatsApp",
    channelInstagram: "Instagram",
    emptyInstagram:
      "No Instagram messages yet — connect Instagram in Settings to get started",
    emptyWhatsapp: "No WhatsApp messages yet — connect WhatsApp in Settings to get started",
    emptyAll: "No conversations found",
    goToSettings: "Go to settings →",
    timeJustNow: "just now",
    timeMin: "{n} min ago",
    timeHour: "{n} h ago",
    timeDay: "{n} d ago",
    unknownContact: "Unknown",
    unreadAria: "Unread messages",
    threadEmpty: "No messages yet. Send a reply to start the conversation.",
    typeImage: "Image",
    typeVideo: "Video",
    typeAudio: "Audio",
    typeDocument: "Document",
    typeLocation: "Location",
    threadErrorTitle: "Error al cargar los mensajes",
    threadErrorDesc: "No se pudieron cargar los mensajes. Inténtalo de nuevo.",
    listErrorTitle: "Error al cargar las conversaciones",
    listErrorDesc: "No se pudieron cargar las conversaciones. Inténtalo de nuevo.",
    noConversationSelected: "No conversation selected",
    selectConversationHint:
      "Select a conversation from the list to view messages, or connect a channel in Settings to start receiving messages.",
    goToWhatsappSettings: "Go to WhatsApp settings →",
    goToInstagramSettings: "Go to Instagram settings →",
  },
  dashboard: {
    title: "Dashboard",
    subtitle: "A snapshot of your workspace activity.",
    kpiOpenConversations: "Open conversations",
    kpiOpenConversationsHint: "Across WhatsApp and Instagram",
    kpiContacts: "Contacts",
    kpiContactsHint: "In your CRM",
    kpiDeals: "Deals",
    kpiDealsHint: "Across all pipelines",
    dealsByStage: "Deals by stage",
    dealsByStageDesc: "Where your open deals sit right now.",
    noDeals: "No deals yet. Create your first pipeline in CRM.",
    recentActivity: "Recent activity",
    recentActivityDesc: "Latest notes, calls, and system events.",
    noActivity: "No activity recorded yet.",
    quickActions: "Quick actions",
    qaOpenInbox: "Open Inbox",
    qaOpenInboxDesc: "Reply to pending conversations",
    qaManageCrm: "Manage CRM",
    qaManageCrmDesc: "Contacts, companies, and deals",
    qaKnowledgeBase: "Knowledge Base",
    qaKnowledgeBaseDesc: "Search docs and chat with the assistant",
    qaWorkspaceSettings: "Workspace settings",
    qaWorkspaceSettingsDesc: "Team, modules, billing, and integrations",
    noStage: "Sin etapa",
  },
  agent: {
    panelTitle: "AI assistant suggestion",
    panelErrorTitle: "Couldn't load the suggestions",
    panelErrorDesc: "Try again to see the assistant's suggestions.",
    approveSend: "Approve and send",
    sendEdited: "Send edited",
    edit: "Edit",
    reject: "Reject",
    settingsTitle: "WhatsApp AI Assistant",
    settingsDescription:
      "Configure how the agent drafts and responds to messages in your conversations.",
    loadErrorTitle: "Error al cargar",
    loadErrorBody: "No se pudo cargar la configuración del asistente IA.",
    mode: "Mode",
    modeCopilot: "Copilot (suggests replies, a human approves)",
    modeAutopilot: "Autopilot (replies on its own within the window)",
    modeHint:
      "Copilot drafts messages. Autopilot sends autonomous replies only if all rules are met.",
    tone: "Tone of voice",
    toneFormal: "Formal (usted)",
    toneCasual: "Casual (tú/vos)",
    toneHint: "Register used in generated responses.",
    brandVoice: "Brand voice",
    brandVoicePlaceholder: "E.g. We answer warmly and quickly, always in Colombian Spanish.",
    autopilotStart: "Autopilot window (start)",
    autopilotEnd: "Autopilot window (end)",
    timezone: "Time zone",
    maxDailyMessages: "Daily message limit (0 = unlimited)",
    maxDiscount: "Maximum discount allowed (%)",
    killSwitch: "Emergency switch",
    killSwitchHint: "Immediately blocks all agent sends.",
    forbiddenTerms: "Forbidden terms (never use in replies)",
    removeAria: "Remove {term}",
    forbiddenPlaceholder: "E.g. total guarantee, free shipping",
    escalateTerms: "Escalation topics (hand off to a human)",
    escalateHint: "If the customer mentions these topics, the agent never replies on its own.",
    escalatePlaceholder: "E.g. lawyer, legal, guarantee, lawsuit",
    consentRequired: "Consent required (Law 1581)",
    consentHint: "Request data-processing authorization before replying autonomously.",
    consentMessage: "Consent message",
    consentPlaceholder:
      "Hi, to serve you we need your authorization to process your personal data in accordance with Law 1581. Do you authorize us? (Reply yes or accept).",
    saveConfig: "Save configuration",
  },
  onboarding: {
    businessTitle: "Tell us about your business",
    businessSubtitle:
      "This helps us prepare your AI assistant to respond over WhatsApp.",
    whatsappReadinessLabel: "Do you have WhatsApp Business?",
    whatsappReadinessHint:
      "The assistant will be able to draft and reply to messages once you connect it.",
    readinessAlready: "Yes, I already have WhatsApp Business",
    readinessPlanning: "Not yet, but I want to set it up",
    readinessNo: "Not for now",
    businessGoalLabel: "What is your main goal?",
    businessGoalPlaceholder:
      "E.g. handle customer questions, take orders, invoice…",
    businessGoalHint: "You can change it later from settings.",
    checklistTitle: "First steps",
    checklistSubtitle:
      "Complete these steps to get your workspace ready.",
    checklistProgress: "{done} of {total} completed",
    stepConnectWhatsApp: "Connect WhatsApp",
    stepConnectWhatsAppDesc:
      "Receive and reply to messages automatically with your number.",
    stepChoosePlan: "Choose a plan",
    stepChoosePlanDesc: "Unlock your assistant's automations.",
    stepMeetAssistant: "Meet your assistant",
    stepMeetAssistantDesc:
      "The assistant drafts replies for you to approve.",
    stepOpenInbox: "Open your inbox",
    stepOpenInboxDesc: "Review and reply to your first conversations.",
    statusDone: "Completed",
    statusTodo: "Pending",
    assistantIntroTitle: "Meet your assistant",
    assistantIntroBody:
      "Your WhatsApp assistant drafts replies to your customers and you approve them before they are sent. It learns about your business as messages arrive.",
    assistantIntroKnowledgeTitle: "Knowledge base",
    assistantIntroKnowledgeBody:
      "Upload documents about your products, prices, and policies so the assistant can answer accurately.",
    assistantIntroCta: "Configure assistant",
    assistantIntroDismiss: "Later",
  },
} as const;

export type Ui = typeof ui;

/** Interpolate `{var}` placeholders in a copy template. */
export function tpl(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) =>
    String(vars[key] ?? "")
  );
}

/**
 * Typed copy lookup. Referencing an unknown key is a compile error.
 * Falls back to the English mirror only if the Spanish value were ever empty,
 * so a label never renders empty.
 */
export function copy<N extends keyof Ui, K extends keyof Ui[N]>(
  namespace: N,
  key: K
): Ui[N][K] {
  const value = ui[namespace][key];
  if (typeof value === "string" && value.length === 0) {
    const enNamespace = en[namespace as keyof typeof en];
    const fallback = enNamespace ? (enNamespace as Record<string, unknown>)[key as string] : undefined;
    return (typeof fallback === "string" ? fallback : value) as Ui[N][K];
  }
  return value;
}
